
version: '3.9'

networks:
  docker-network:
    name: inception
    driver: bridge

services:
  # Web Server
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports: 
      - "443:443"
    # depends_on: 
    #   - wordpress
    # volumes:
    #   - wp:/var/www/wordpress
    networks:
      - docker-network
    restart: on-failure
  # Wordpress service
#   wordpress:
#     container_name: wordpress
#     build: ./requirements/wordpress/.
#     depends_on: 
#       - mariadb
#     volumes:
#       - wp:/var/www/wordpress
#     env_file:
#       - .env
#     networks:
#       - inception
#     restart: on-failure
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
       - docker-network
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  # wordpress:
  #   driver: local
  #   name: wp
  #   driver_opts:
  #     device: "/home/yuboktae/data/wp"
  #     o: "bind"
  #     type: "none"
  mariadb:
    driver: local
    name: db
    driver_opts:
      device: "/home/yuboktae/data/db"
      o: "bind"
      type: "none"