
version: '3.9'

networks:
  docker-network:
    name: inception

services:
  # Web Server
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports: 
      - "443:443"
    # depends_on: 
    #   - wordpress
    # volumes:
    #   - wordpress:/var/www/html
    networks:
      - docker-network
    restart: always
  # Wordpress service
#   wordpress:
#     container_name: wordpress
#     build: ./requirements/wordpress/.
#     depends_on: 
#       - mariadb
#     volumes:
#       - wordpress:/var/www/html
#     env_file:
#       - .env
#     networks:
#       - inception
#     restart: always
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
       - docker-network
    ports:
      - "3306:3306"
    restart: always

#   wordpress:
#     driver: local
#     name: wordpress
#     device: /home/yuboktae/data/wordpress
#     o: bind
#     type: none
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      device: /home/yuboktae/data/mariadb
      o: bind
      type: none