
version: '3.9'

networks:
  docker-network:
    name: inception
    driver: bridge

services:
  # Web Server
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports: 
      - "443:443"
    depends_on: 
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - docker-network
    restart: always
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
       - docker-network
    restart: always
  # Wordpress service
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on: 
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - docker-network
    restart: always

volumes:
  wordpress:
    driver: local
    name: wp
    driver_opts:
      device: "/home/yuboktae/data/wp"
      o: "bind"
      type: "none"
  mariadb:
    driver: local
    name: db
    driver_opts:
      device: "/home/yuboktae/data/db"
      o: "bind"
      type: "none"